version: '2'
services:
    elasticsearch:
        image: elasticwiki
        container_name: elasticsearch
        mem_limit: 2g
        memswap_limit: 2g 
        environment:
            - "discovery.type=single-node"
            - "ES_HEAP_SIZE=1g"
        volumes: 
            - ../elasticdata:/usr/share/elasticsearch/data:rw
        ports:
            - "9200:9200"
        restart: unless-stopped
    kibana:
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:6.5.4
        ports:
            - "5601:5601"
        restart: unless-stopped
